### ISSUE TITLE
carthage update fails at building crypto swift

### ISSUE THREAD

**Issue by SNThunderbolt** [RooyeKhat-Media/iGap-iOS#1]
Hi i'm trying to work with the code but when i try updating the carthage it fails at building the crypto swift and gives the following error:

Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/nouri/Desktop/iOSTst/SourceCodes/iGap-iOS-master/Carthage/Checkouts/CryptoSwift/CryptoSwift.xcworkspace -scheme CryptoSwift -configuration Release -derivedDataPath /Users/nouri/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CryptoSwift/0.7.2 -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/nouri/Desktop/iOSTst/SourceCodes/iGap-iOS-master/Carthage/Checkouts/CryptoSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2s/9v46w0b97_v60x1wg2n9zr_h0000gn/T/carthage-xcodebuild.4oyD4p.log

**Comment by alternatiph** [comment]
Sajedeh, we are aware of this problem. In the next commit this problem will be solved.

**Comment by SNThunderbolt** [comment]
Keyvan! Appreciate your support and awesome work. :)
Good Luck!

**Comment by RooyeKhat** [comment]
@SNThunderbolt tested now 
Fix problem .

**Comment by bidhan01071992** [comment]
I am having this error after updating the code to swift 4

*** Fetching CryptoSwift
*** Checking out CryptoSwift at "0.8.2"
*** xcodebuild output can be found in /var/folders/q7/kzdpqpl574s96x0r14srrx0rwybxpt/T/carthage-xcodebuild.VZpOw3.log
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/cbidhan/Desktop/SharedCalendar/Carthage/Checkouts/CryptoSwift/CryptoSwift.xcworkspace -scheme CryptoSwift -configuration Release -derivedDataPath /Users/cbidhan/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/CryptoSwift/0.8.2 -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/q7/kzdpqpl574s96x0r14srrx0rwybxpt/T/CryptoSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/cbidhan/Desktop/SharedCalendar/Carthage/Checkouts/CryptoSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/q7/kzdpqpl574s96x0r14srrx0rwybxpt/T/carthage-xcodebuild.VZpOw3.log

**Comment by yanellyjm** [comment]
I'm having same issue:
CryotSwift.version      = "0.8.2"
swift_version = "4.0.3"
s.osx.deployment_target = "10.9"
...................................................
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/xcodeserver_svc/workspace/p_ios_feature_devops_ED-836-TE3CEIFCGH7DFUDKDPHPRZEBHKXJ642JZZAOTLYAXEU3C4N6CHFA/Agent/Carthage/Checkouts/CryptoSwift/CryptoSwift.xcworkspace -scheme CryptoSwift -configuration Release -derivedDataPath /Users/xcodeserver_svc/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/CryptoSwift/0.8.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/xcodeserver_svc/workspace/p_ios_feature_devops_ED-836-TE3CEIFCGH7DFUDKDPHPRZEBHKXJ642JZZAOTLYAXEU3C4N6CHFA/Agent/Carthage/Checkouts/CryptoSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/28/rjyj5r597fgc7myzw0zknyjc0000gp/T/carthage-xcodebuild.wZyFVo.log
[Pipeline] }
