### ISSUE TITLE
mute / unmute rooms

### ISSUE THREAD

**Issue by RooyeKhat** [RooyeKhat-Media/iGap-iOS#10]
Add mute and unmute sync from server 

> Read More : 
> https://github.com/RooyeKhat-Media/iGap-API/blob/master/docs/guide/v1/request/client/MuteRoom.md

**Comment by saeedrooyekhat** [comment]
Done due to the 10fe7cce409afd8f33809ffcf819e4d86712de6f / dcd80ec7b5e278f754d4f4d301e6cbf77fcf9f30
