### ISSUE TITLE
Add report capability

### ISSUE THREAD

**Issue by RooyeKhat** [RooyeKhat-Media/iGap-iOS#12]
Add report capability
User , Room and Message Report 

> Read More : 
> https://github.com/RooyeKhat-Media/iGap-API/blob/master/docs/guide/v1/request/user/Report.md
> https://github.com/RooyeKhat-Media/iGap-API/blob/master/docs/guide/v1/request/client/RoomReport.md

**Comment by saeedrooyekhat** [comment]
Done due to the e1f2753c86cc8ba786dd70b67ce1428027dd030a and 288ffd08179178a447364104db977899ca496d69
