### ISSUE TITLE
Preparing for the release 0.1.2

### ISSUE THREAD

**Issue by RooyeKhat** [RooyeKhat-Media/iGap-iOS#13]
Preparing for the release 0.1.2
Task List :
- [ ] #4 
- [x] #5 
- [ ] #10 
- [ ] #11 
- [ ] #12

**Comment by alternatiph** [comment]
Tracking this in [Milestone 0.1.2](https://github.com/RooyeKhat-Media/iGap-iOS/milestone/1)
